/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecosystemsandbox;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bbaago
 */
public class EcosystemSandboxNew extends java.awt.Dialog {

    /**
     * Creates new form EcosystemSandboxNew
     */
    public EcosystemSandboxNew(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Ecosystem Sandbox - New Ecosystem");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel3.setText("Create a new environment.");
        add(jLabel3, java.awt.BorderLayout.NORTH);

        jLabel1.setText("Area (m2)");
        jLabel1.setName("lblArea"); // NOI18N
        jPanel1.add(jLabel1);

        txtArea.setColumns(7);
        txtArea.setName("txtArea"); // NOI18N
        txtArea.setNextFocusableComponent(txtHeight);
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });
        jPanel1.add(txtArea);

        jPanel2.add(jPanel1);

        jLabel2.setText("Atmosphere Height (m)");
        jLabel2.setName("lblAtmosphere"); // NOI18N
        jPanel2.add(jLabel2);

        txtHeight.setColumns(5);
        txtHeight.setName("txtHeight"); // NOI18N
        txtHeight.setNextFocusableComponent(jButton1);
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        jPanel2.add(txtHeight);

        add(jPanel2, java.awt.BorderLayout.WEST);

        jButton1.setText("Submit");
        jButton1.setName("btnSubmit"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int area;
        int height;
        area = Integer.parseInt(this.txtArea.getText());
        height = Integer.parseInt(this.txtHeight.getText());
        Ecosystem earth = new Ecosystem(area,height);
        this.setVisible(false);
        new EcosystemSandboxMain(earth).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtHeight;
    // End of variables declaration//GEN-END:variables
}
